# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-10-06 08:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='talk',
            old_name='speaker',
            new_name='smiles',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='scheduled_at',
        ),
        migrations.RemoveField(
            model_name='talk',
            name='topic',
        ),
    ]
