name: Tools Package
on:
  workflow_dispatch: { }
  push:
    paths:
      - 'tools/**'
jobs:
  check:
    runs-on: ubuntu-20.04
    name: Check version was changed
    outputs:
      changed_version: ${{ steps.check-version.outputs.changed_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Check version was changed
        id: check-version
        working-directory: ./tools
        run: |
          name="$(jq .name package.json | sed 's/"//g')"
          current_version="$(jq .version package.json | sed 's/"//g')"
          npm_response="$(curl -s --retry 3 "https://registry.npmjs.org/${name}/${current_version}")"
          if [[ $npm_response == "\"version not found: ${current_version}\"" ]] || [[ $npm_json == "\"Not Found\"" ]]; then
            changed_version='true'
          else
            changed_version='false'
          fi
          echo '::echo::on'
          echo "::set-output name=changed_version::${changed_version}"
          echo '::echo::off'

  build:
    name: Build and publish to npm
    runs-on: ubuntu-20.04
    needs: check
    environment: Prod
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.WRITE_TOKEN }}
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '12.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Upgrade npm
        run: npm install -g npm@latest
      - name: npm version
        run: npm version
      - run: npm install
        working-directory: ./tools
      - run: npm publish
        working-directory: ./tools
        if: github.ref == 'refs/heads/master' && needs.check.outputs.changed_version == 'true'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Commit package-lock.json
        if: github.ref == 'refs/heads/master' && needs.check.outputs.changed_version == 'true'
        run: |
          if [ -n "$(git status -s tools/package-lock.json)" ]; then
            git config --global user.name 'GitHub Actions'
            git config --global user.email 'spodolskaya@datagrok.ai'
            git pull
            git add tools/package-lock.json
            git commit -m "GitHub Actions: Update tools/package-lock.json [skip ci]"
            count=0
            until git push; do
              exit=$?
              wait=$((2 ** count))
              count=$((count + 1))
              if [ $count -lt "10" ]; then
                echo "Retry $count/$retries exited $exit, retrying 'git push' in $wait seconds..."
                sleep $wait
                git pull --rebase
              else
                echo "Retry $count/$retries exited $exit, no more retries left for 'git push'."
                exit $exit
              fi
            done
          fi
